[package]
name = "roestige-gentenair"
version = "0.1.0"
authors = ["Jan Vandepitte <Jan.Vandepitte@sirus.be>"]
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0.0-alpha.2"
actix-files = "0.1.0-alpha.1"
actix-session = "0.1.0-alpha.2"

futures = "0.1.25"
env_logger = "0.5"
bytes = "0.4